-- Glenair Data Seeding

INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-375-20', 'Pin', '20', '26÷20', '0,15-0,6', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40579', 'Pin', '18', '26÷20', '0,15÷0,6', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40553', 'Pin', '16S', '18÷16', '1÷1,5', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40553-12', 'Pin', '16S', '20', '0.6', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40553-13*', 'Pin', '16S', '26÷20', '0,15÷0,6', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40553-15*', 'Pin', '16S', '18', '0,75-1,0', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40553-20', 'Pin', '16S', '14', '2', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40553-26', 'Pin', '16S', '12', '2,5-3,0', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40557', 'Pin', '16', '18÷16', '1÷1,5', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40557L', 'Pin', '16', '18÷16', '1÷1,5', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40557-08*', 'Pin', '16', '26÷24', '0,15÷0,2', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40557-12*', 'Pin', '16', '20', '0,6', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40557-13*', 'Pin', '16', '26÷20', '0,15÷0,6', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40557-15*', 'Pin', '16', '18', '0,75-1,0', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40557-20**', 'Pin', '16', '14', '2', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40557-22**', 'Pin', '16', '/', '2,5', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40557-22L**', 'Pin', '16', '/', '2,5', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40557-26**', 'Pin', '16', '12', '2,5-3,0', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40557-32*', 'Pin', '16', '32÷28', '/', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40561', 'Pin', '12', '12', '2,5-3,0', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40561-12*', 'Pin', '12', '20', '0,6', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40561-15*', 'Pin', '12', '18', '0,75-1,0', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40561-177*', 'Pin', '12', '18-16', '1,5', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40561-20*', 'Pin', '12', '14', '2', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40561-22*', 'Pin', '12', '/', '2,5', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40561-30**', 'Pin', '12', '/', '4-5', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40561-30M**', 'Pin', '12', '/', '4', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40561-38**', 'Pin', '12', '10', '6', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40792', 'Pin', '8', '8', '9', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40792-15*', 'Pin', '8', '18', '0,75-1,0', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40792-18*', 'Pin', '8', '18÷14', '1÷2', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40792-20*', 'Pin', '8', '14', '2', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40792-26*', 'Pin', '8', '12', '2,5-3,0', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40792-30*', 'Pin', '8', '/', '4-5', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40792-38*', 'Pin', '8', '10', '6', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40792-50**', 'Pin', '8', '/', '10', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40792-58**', 'Pin', '8', '6', '13,2', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4P', 'Pin', '4', '4', '22-25', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4P-22*', 'Pin', '4', '/', '2,5', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4P-25', 'Pin', 'Replaced by 10-113474-4P', '', '', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4P-26*', 'Pin', '4', '12', '2,5-3,0', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4P-30*', 'Pin', '4', '/', '4-5', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4P-38*', 'Pin', '4', '10', '6', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4P-50*', 'Pin', '4', '/', '10', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4P-58*', 'Pin', '4', '6', '13,2', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4P-62*', 'Pin', '4', '/', '16', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1P', 'Pin', '0', '0', '50-60', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1P-107*', 'Pin', '0', '/', '50', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1P-72*', 'Pin', '0', '4', '22-25', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1P-35*', 'Pin', '0', '/', '35', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1P-45*', 'Pin', '0', '8', '9', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1P-50*', 'Pin', '0', '/', '10', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1P-58*', 'Pin', '0', '6', '13,2', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1P-62*', 'Pin', '0', '/', '16', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-0P*', 'Pin', '4/0', '4/0', '107', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-0P-78*', 'Pin', '4/0', '4', '22-25', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-0P-107*', 'Pin', '4/0', '/', '50', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-0P-144*', 'Pin', '4/0', '/', '70', 'Glenair Series 80 Pin Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40520LC', 'Socket', '20', '26-20', '0,15-0,6', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40588', 'Socket', '18', '26-20', '0,15-0,6', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40552', 'Socket', '16S', '18-16', '1-1,5', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40552-12*', 'Socket', '16S', '20', '0,6', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40552-13*', 'Socket', '16S', '26-20', '0,15-0,6', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40552-15*', 'Socket', '16S', '18', '0,75-1', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40552-20**', 'Socket', '16S', '14', '2', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40552-26**', 'Socket', '16S', '12', '2,5-3,0', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40556', 'Socket', '16', '18-16', '1-1,5', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40556-08*', 'Socket', '16', '26-24', '0,15-0,2', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40556-12*', 'Socket', '16', '20', '0,6', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40556-13*', 'Socket', '16', '26-20', '0,15-0,6', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40556-15*', 'Socket', '16', '18', '0,75-1', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40556-20**', 'Socket', '16', '14', '2', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40556-22**', 'Socket', '16', '/', '2,5', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40556-26**', 'Socket', '16', '12', '2,5-3,0', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40556-32*', 'Socket', '16', '32-28', '/', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40560', 'Socket', '12', '12', '2,5-3,0', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40560-12*', 'Socket', '12', '20', '0,6', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40560-15*', 'Socket', '12', '18', '0,75-1', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40560-177*', 'Socket', '12', '18-16', '1,5', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40560-20*', 'Socket', '12', '14', '2', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40560-22*', 'Socket', '12', '/', '2,5', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40560-30**', 'Socket', '12', '/', '4-5', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40560-30M**', 'Socket', '12', '/', '4', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40560-38**', 'Socket', '12', '10', '6', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40793-1', 'Socket', '8', '8', '9', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40793-1-15*', 'Socket', '8', '18', '0,75-1', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40793-1-18*', 'Socket', '8', '18-14', '1-2', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40793-1-20*', 'Socket', '8', '14', '2', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40793-1-26*', 'Socket', '8', '12', '2,5-3,0', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40793-1-30*', 'Socket', '8', '/', '4-5', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40793-1-38*', 'Socket', '8', '10', '6', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40793-1-50**', 'Socket', '8', '/', '10', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-40793-1-58**', 'Socket', '8', '6', '13,2', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4S-1', 'Socket', '4', '4', '22-25', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4S-1-22*', 'Socket', '4', '/', '2,5', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4S-1-25', 'Socket', 'Replaced by 10-113474-4S-1', '', '', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4S-1-26*', 'Socket', '4', '12', '2,5-3,0', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4S-1-30*', 'Socket', '4', '/', '4-5', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4S-1-38*', 'Socket', '4', '10', '6', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4S-1-50*', 'Socket', '4', '/', '10', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4S-1-58*', 'Socket', '4', '6', '13,2', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-4S-1-62*', 'Socket', '4', '/', '16', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1S', 'Socket', '0', '0', '50-60', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1S-107*', 'Socket', '0', '/', '50', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1S-72*', 'Socket', '0', '4', '22-25', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1S-35*', 'Socket', '0', '/', '35', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1S-45*', 'Socket', '0', '8', '9', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1S-50*', 'Socket', '0', '/', '10', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1S-58*', 'Socket', '0', '6', '13,2', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-1S-62*', 'Socket', '0', '/', '16', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-0S', 'Socket', '4/0', '4/0', '107', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-0S-78*', 'Socket', '4/0', '4', '22-25', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-0S-107*', 'Socket', '4/0', '/', '50', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_contacts (part_number, type, contact_size, awg_range, mm2_range, description) VALUES ('10-113474-0S-144*', 'Socket', '4/0', '/', '70', 'Glenair Series 80 Socket Contact');
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('10SL-3', 3, '16S', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('10SL-4', 2, '16S', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('14S-1', 3, '16S', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('14S-2', 4, '16S', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('14S-5', 5, '16S', 5);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('14S-6', 6, '16S', 6);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('14S-7', 3, '16S', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('14S-9', 2, '16S', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('14S-07', 7, '16S', 7);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('16S-1', 7, '16S', 7);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('16S-4', 2, '16S', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('16S-5', 3, '16S', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('16S-8', 5, '16S', 5);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('16-2', 1, '12', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('16-7', 3, '8', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('16-7', 3, '16', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('16-9', 4, '12', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('16-9', 4, '16', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('16-10', 3, '12', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('16-11', 2, '12', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('16-12', 1, '4', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('16-A10', 10, '18', 10);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-1', 10, '16', 10);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-3', 2, '12', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-4', 4, '16', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-5', 3, '12', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-5', 3, '16', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-6', 1, '4', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-06', 6, '12', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-06', 6, '16', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-7', 1, '8', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-8', 8, '12', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-8', 8, '16', 7);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-9', 7, '12', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-9', 7, '16', 5);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-10', 4, '12', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-10S MT', 4, '12', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-11', 5, '12', 5);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-12', 6, '16', 6);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-13', 4, '8', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-13', 4, '12', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-16', 1, '12', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-19', 10, '16', 10);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-20', 5, '16', 5);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-22', 3, '16', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('18-30 (18-20x110°)', 5, '16', 5);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-2', 1, '0', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-3', 3, '12', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-4', 4, '12', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-6', 3, '16', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-7', 8, '16', 8);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-8', 6, '8', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-8', 6, '16', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-9', 8, '12', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-9', 8, '16', 7);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-11', 13, '16', 13);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-14', 5, '8', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-14', 5, '12', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-15', 7, '12', 7);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-16', 9, '12', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-16', 9, '16', 7);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-17', 6, '12', 5);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-17', 6, '16', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-18', 9, '12', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-18', 9, '16', 6);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-19', 3, '8', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-21', 9, '12', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-21', 9, '16', 8);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-22', 6, '8', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-22', 6, '16', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-23', 2, '8', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-24', 4, '8', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-24', 4, '16', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-A24', 4, '8', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-A24', 4, '16', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-25 (20-11x100°)', 13, '16', 13);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-27', 14, '16', 14);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-29', 17, '16', 17);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-30 (20-11x250°)', 13, '16', 13);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-33', 11, '16', 11);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-A8', 8, '8', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-A8', 8, '16', 6);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-A9', 9, '12', 9);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-A48', 19, '16', 19);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-B8', 8, '12', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('20-B8', 8, '16', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-1', 2, '8', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-2', 3, '8', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-4', 4, '8', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-4', 4, '12', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-5', 6, '12', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-5', 6, '16', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-7', 1, '0', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-9', 3, '12', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-10', 4, '16', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-11', 2, '16', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-12', 5, '8', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-12', 5, '16', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-14', 19, '16', 19);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-15', 6, '12', 5);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-15', 6, '16', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-17', 9, '12', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-17', 9, '16', 8);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-18', 8, '16', 8);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-19', 14, '16', 14);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-20', 9, '16', 9);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-21', 3, '0', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-21', 3, '16', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-22', 4, '8', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-23', 8, '12', 8);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-27', 9, '8', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-27', 9, '16', 8);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-28', 7, '12', 7);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-34', 5, '12', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-34', 5, '16', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-82', 10, '8', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-82', 10, '16', 8);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-A10', 10, '16', 10);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-A37', 37, '18', 37);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('22-22S MT', 4, '8', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-2', 7, '12', 7);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-3', 7, '12', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-3', 7, '16', 5);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-4', 4, '0', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-4', 4, '16', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-5', 16, '16', 16);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-06', 6, '8', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-06', 6, '16', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-6', 8, '12', 8);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-07', 7, '12', 7);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-7', 16, '12', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-7', 16, '16', 14);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-9', 2, '4', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-10', 7, '8', 7);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-11', 9, '8', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-11', 9, '12', 6);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-12', 5, '4', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-12', 5, '12', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-013', 13, '12', 6);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-013', 13, '16', 7);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-19', 12, '16', 12);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-20', 11, '12', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-20', 11, '16', 9);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-22', 4, '8', 4);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-27', 7, '16', 7);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-28', 24, '16', 24);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-67', 19, '12', 19);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-A1', 1, '0', 1);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-A8', 8, '8', 5);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-A8', 8, '16', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-A11', 11, '8', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-A11', 11, '16', 9);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-A12', 12, '4', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-A12', 12, '16', 10);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-A14', 14, '4', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-A14', 14, '16', 12);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-A25', 25, '16', 25);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-A28', 28, '16', 28);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-A55*', 55, '20', 55);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('24-G5', 5, '8', 5);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('28-1', 9, '8', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('28-1', 9, '12', 6);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('28-2', 14, '12', 2);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('28-2', 14, '16', 12);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('28-3', 3, '8', 3);
INSERT OR REPLACE INTO glenair_arrangements (arrangement, total_contacts, contact_size, contact_count) VALUES ('28-6', 3, '4', 3);
INSERT OR IGNORE INTO glenair_wire_contacts (wire_size, system, contact_size) VALUES ('20', 'AWG', '20');
INSERT OR IGNORE INTO glenair_wire_contacts (wire_size, system, contact_size) VALUES ('22', 'AWG', '20');
INSERT OR IGNORE INTO glenair_wire_contacts (wire_size, system, contact_size) VALUES ('24', 'AWG', '20');
INSERT OR IGNORE INTO glenair_wire_contacts (wire_size, system, contact_size) VALUES ('26', 'AWG', '20');
INSERT OR IGNORE INTO glenair_wire_contacts (wire_size, system, contact_size) VALUES ('16', 'AWG', '16');
INSERT OR IGNORE INTO glenair_wire_contacts (wire_size, system, contact_size) VALUES ('16', 'AWG', '16S');
INSERT OR IGNORE INTO glenair_wire_contacts (wire_size, system, contact_size) VALUES ('18', 'AWG', '16');
INSERT OR IGNORE INTO glenair_wire_contacts (wire_size, system, contact_size) VALUES ('12', 'AWG', '12');
INSERT OR IGNORE INTO glenair_wire_contacts (wire_size, system, contact_size) VALUES ('8', 'AWG', '8');
INSERT OR IGNORE INTO glenair_wire_contacts (wire_size, system, contact_size) VALUES ('4', 'AWG', '4');
INSERT OR IGNORE INTO glenair_wire_contacts (wire_size, system, contact_size) VALUES ('0', 'AWG', '0');
